#!/bin/bash
# Copyright 2013 Canonical Ltd.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; version 2.1.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Author: Zoltán Balogh <zoltan.balogh@canonical.com>

. `dirname $0`/functions.inc

LOCAL_TIME_STAMP=`date +20%y%m%d-%H%M%S`

phablet-screenshot -s ${SERIALNUMBER} /tmp/screenshot-${LOCAL_TIME_STAMP}.png
xdg-open /tmp/screenshot-${LOCAL_TIME_STAMP}.png
