#!/bin/bash
# Copyright 2013 Canonical Ltd.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; version 2.1.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Author: Zoltán Balogh <zoltan.balogh@canonical.com>
#         Juhapekka Piiroinen <juhapekka.piiroinen@canonical.com>

. `dirname $0`/functions.inc

LOCAL_DATE=`date +%Y%m%d`
LOCAL_TIME=`date +%T`
TIMEZONE=`cat /etc/timezone`

adb_shell sed -i "s#.*/.*#${TIMEZONE=}#" /etc/timezone
adb_shell dpkg-reconfigure --frontend noninteractive tzdata > /dev/null
adb_shell date +%Y%m%d -s "${LOCAL_DATE}" > /dev/null
adb_shell date +%T -s "${LOCAL_TIME}" > /dev/null

