#!/bin/bash
# Copyright 2013 Canonical Ltd.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; version 2.1.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Author: Juhapekka Piiroinen <juhapekka.piiroinen@canonical.com>

. `dirname $0`/functions.inc
shift

SSHPORT=$1
shift

QMLPORT=$1
shift

if [[ -z $SSHPORT ]]; then
  SSHPORT=2222
fi

if [[ -z $QMLPORT ]]; then
  QMLPORT=3768
fi

adb_forward_tcp ${SSHPORT} 22
adb_forward_tcp ${QMLPORT} 3768

while (( "$#" )); do

echo "Port ${1}"
adb_forward_tcp ${1} ${1}
shift

done
