#!/bin/bash
# Copyright 2013 Canonical Ltd.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; version 2.1.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Author: Juhapekka Piiroinen <juhapekka.piiroinen@canonical.com>

. `dirname $0`/functions.inc

adb_shell getprop "ro.product.model"
adb_shell getprop "ro.product.name"
device_image_hardware
device_image_version
#adb_shell uname -p|sed 's/v7l/hf/'
adb_shell 'dpkg --print-architecture 2>/dev/null '
adb_shell click framework list|sort -n|egrep "^ubuntu-sdk-[0-9]{2}\.[0-9]{2}[[:space:]]$"|tail -1
