#!/bin/bash
# Copyright 2013 Canonical Ltd.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; version 2.1.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Author: Juhapekka Piiroinen <juhapekka.piiroinen@canonical.com>

if [ "$1" = "1" ]; then
    adb kill-server > /dev/null
    adb start-server > /dev/null
fi

IFS=$'\n'

for DEVICES_INFO in `adb devices -l | grep -Ev "List of devices attached" | grep -Ev "emulator-" | sed "/^$/d"`
do
        if [[ ${DEVICES_INFO} =~ ^([a-zA-Z0-9]+)(.*)$ ]]; then
                NAME="${BASH_REMATCH[1]}"
                REST="${BASH_REMATCH[2]}"
		ARCH=`adb -s ${NAME} shell dpkg --print-architecture 2>&1|egrep -v "device not found"`
                if [ $? -ne 0 ]
		then
			continue
		fi
		ARCH=${ARCH/arm*/armhf}
                ARCH=${ARCH//[[:blank:]]/}
                echo "$NAME$REST arch:$ARCH"
        fi
done
