#!/bin/bash
# Copyright 2013 Canonical Ltd.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; version 2.1.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Author: Juhapekka Piiroinen <juhapekka.piiroinen@canonical.com>

SCRIPTPATH=`dirname $0`

DISPLAYNAME=$1
PROJECTFILES=${@:2}

SOURCEFILES=

for PROJECTFILE in ${PROJECTFILES}; do
   case ${PROJECTFILE} in
     *tests*) ;; 									# ignore tests folder
     *qml) SOURCEFILES+="${PROJECTFILE#$PWD/} ";;
   esac
done

############################################################
echo
echo "Creating po/${DISPLAYNAME}.pot from"
for SOURCEFILE in ${SOURCEFILES}; do
   echo ${SOURCEFILE}
done
############################################################

mkdir -p po
xgettext -o po/${DISPLAYNAME}.pot --qt --c++ --add-comments=TRANSLATORS --keyword=tr --keyword=tr:1,2 ${SOURCEFILES} --from-code=UTF-8
echo "..created!"
