#!/bin/bash
# Copyright 2014 Canonical Ltd.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; version 2.1.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Author: David Barth <david.barth@canonical.com>

SCRIPTPATH=`dirname $0`
PROJECTPATH=$1

if [[ -z ${PROJECTPATH} ]]; then
  PROJECTPATH=`pwd`
fi

CORDOVA_PACKAGE="ubuntu-html5-platform-3.4-dev"
PAYLOAD_DIR="usr/share/ubuntu-html5-platform-3.4/"
CORDOVA_CACHE=${HOME}/.cache/ubuntu-html5-platform

download_arch () {
    ARCH2=$1
    ARCH3=$2

    [ -z "$ARCH2" -o -z "$ARCH3" ] && exit "download_arch"

    ARCH=`apt-config dump | grep "APT::Architecture " | cut -d\" -f2`
    URI=`apt-get download --print-uris ${CORDOVA_PACKAGE} | grep ^\' | cut -d\' -f2`
    PACKAGE_FILENAME=`apt-get download --print-uris ${CORDOVA_PACKAGE} | grep ^\' | cut -d\  -f2 | sed "s/_${ARCH}.deb$/_${ARCH2}.deb/"`

    mkdir -p ${CORDOVA_CACHE}/lib/${ARCH3}

    (
        cd /tmp
        wget `echo $URI | sed "s/_${ARCH}.deb$/_${ARCH2}.deb/"`

	# plain extraction since the packages are already configured w/ arch specific install paths
        dpkg-deb -x ${PACKAGE_FILENAME} ${CORDOVA_CACHE}/download

        rm -f ${PACKAGE_FILENAME}
    )
}

install_arch () {
    ARCH3=$1

    [ -z "$ARCH3" ] && exit "install_arch"

    mkdir -p ${CORDOVA_CACHE}/lib/${ARCH3}
    mkdir -p ${CORDOVA_CACHE}/www/cordova

    rm -rf ${CORDOVA_CACHE}/download/${PAYLOAD_DIR}/${ARCH3}/cordova-ubuntu

    cp -Rf ${CORDOVA_CACHE}/download/${PAYLOAD_DIR}/${ARCH3}/CordovaUbuntu.?.? ${CORDOVA_CACHE}/lib/${ARCH3}
    cp -Rf ${CORDOVA_CACHE}/download/${PAYLOAD_DIR}/${ARCH3}/qml ${CORDOVA_CACHE}
    cp -Rf ${CORDOVA_CACHE}/download/${PAYLOAD_DIR}/${ARCH3}/www/plugins ${CORDOVA_CACHE}/www/cordova
    cp -Rf ${CORDOVA_CACHE}/download/${PAYLOAD_DIR}/${ARCH3}/www/cordova.js ${CORDOVA_CACHE}/www/cordova
    cp -Rf ${CORDOVA_CACHE}/download/${PAYLOAD_DIR}/${ARCH3}/www/cordova_plugins.js ${CORDOVA_CACHE}/www/cordova

    cp ${CORDOVA_CACHE}/download/${PAYLOAD_DIR}/${ARCH3}/www/libcoreplugins.so ${CORDOVA_CACHE}/www/libcoreplugins-${ARCH3}.so

    rm -rf ${CORDOVA_CACHE}/download/${PAYLOAD_DIR}/${ARCH3}
}


echo
echo "Trying to download a pre-built Cordova runtime to accelerate project creation..."
echo

rm -rf ${CORDOVA_CACHE}

download_arch "i386" "i386-linux-gnu"
download_arch "amd64" "x86_64-linux-gnu"
download_arch "armhf" "arm-linux-gnueabihf"

install_arch "i386-linux-gnu"
install_arch "x86_64-linux-gnu"
install_arch "arm-linux-gnueabihf"

find ${CORDOVA_CACHE}
