#!/bin/bash
# Copyright 2013 Canonical Ltd.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; version 2.1.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Author: Benjamin Zeller <benjamin.zeller@canonical.com>

SCRIPTPATH=`dirname $0`
EMULATOR=$1

#wait for the emulator to go away
while pid=$("${SCRIPTPATH}/local_emulator_pid" "${EMULATOR}"); 
do
  "${SCRIPTPATH}/local_stop_emulator" "${EMULATOR}"
  sleep 0.5;
done;

set -e
ubuntu-emulator destroy "${EMULATOR}" --yes
set +e


