#!/bin/bash
# Copyright 2013 Canonical Ltd.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; version 2.1.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Author: Zoltán Balogh <zoltan.balogh@canonical.com>

SCRIPTPATH=`dirname $0`
EMULATOR=$1
MEMORY=$2
SCALE=$3

PID=$(${SCRIPTPATH}/local_emulator_pid ${EMULATOR})
if [ ! -z "${PID}" ]
then
  echo "Emulator already running with pid ${PID}"
  exit 1
fi

set -e
ubuntu-emulator run ${EMULATOR} --memory=${MEMORY} --scale=${SCALE} &
set +e
