#!/bin/bash
# Copyright 2014 Canonical Ltd.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; version 2.1.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Author: David Barth <david.barth@canonical.com>

SCRIPTPATH=`dirname $0`
PROJECTPATH=$1

if [[ -z ${PROJECTPATH} ]]; then
  PROJECTPATH=`pwd`
fi

CORDOVA_PACKAGE="ubuntu-html5-platform-3.4-dev"
PAYLOAD_DIR="/usr/share/ubuntu-html5-platform-3.4/"
CORDOVA_CACHE=${HOME}/.cache/ubuntu-html5-platform

download_arch () {
    ARCH2=$1
    ARCH3=$2

    [ -z "$ARCH2" -o -z "$ARCH3" ] && exit "download_arch"

    ARCH=`apt-config dump | grep "APT::Architecture " | cut -d\" -f2`
    URI=`apt-get download --print-uris ${CORDOVA_PACKAGE} | grep ^\' | cut -d\' -f2`
    PACKAGE_FILENAME=`apt-get download --print-uris ${CORDOVA_PACKAGE} | grep ^\' | cut -d\  -f2 | sed "s/_${ARCH}.deb$/_${ARCH2}.deb/"`

    mkdir -p ${CORDOVA_CACHE}/lib/${ARCH3}

    (
        cd /tmp
        wget `echo $URI | sed "s/_${ARCH}.deb$/_${ARCH2}.deb/"`

	# extract in plain lib since the packages are already configured w/ arch specific install paths
        dpkg-deb -x ${PACKAGE_FILENAME} ${CORDOVA_CACHE}/lib

        rm -f ${PACKAGE_FILENAME}
    )
}

install_arch () {
    ARCH3=$1

    [ -z "$ARCH3" ] && exit "install_arch"

    mv ${CORDOVA_CACHE}/lib/${PAYLOAD_DIR}/${ARCH3}/* ${CORDOVA_CACHE}/lib/${ARCH3}

    for f in `find ${CORDOVA_CACHE}/lib/${ARCH3} | grep .so$`
    do
        mv ${f} ${CORDOVA_CACHE}/lib/${ARCH3}
    done

    cp -Rf ${CORDOVA_CACHE}/lib/${ARCH3}/CordovaUbuntu.?.? ${CORDOVA_CACHE}
    cp -Rf ${CORDOVA_CACHE}/lib/${ARCH3}/www/* ${CORDOVA_CACHE}/CordovaUbuntu.?.?
    cp -Rf ${CORDOVA_CACHE}/lib/${ARCH3}/qml/* ${CORDOVA_CACHE}/CordovaUbuntu.?.?

    rm -rf ${CORDOVA_CACHE}/lib/${ARCH3}/${PAYLOAD_DIR}
    rm -rf ${CORDOVA_CACHE}/lib/${ARCH3}/usr
    rm -rf ${CORDOVA_CACHE}/lib/${ARCH3}/www
    rm -rf ${CORDOVA_CACHE}/lib/${ARCH3}/qml
    rm -rf ${CORDOVA_CACHE}/lib/${ARCH3}/CordovaUbuntu.?.?
}


echo
echo "Trying to download a pre-built Cordova runtime to accelerate project creation..."
echo

rm -rf ${CORDOVA_CACHE}

download_arch "i386" "i386-linux-gnu"
download_arch "amd64" "x86_64-linux-gnu"
download_arch "armhf" "arm-linux-gnueabihf"

install_arch "i386-linux-gnu"
install_arch "x86_64-linux-gnu"
install_arch "arm-linux-gnueabihf"

find ${CORDOVA_CACHE}
