#!/bin/bash
# Copyright 2013 Canonical Ltd.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; version 2.1.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Author: Juhapekka Piiroinen <juhapekka.piiroinen@canonical.com>

. `dirname $0`/functions.inc
shift

FOLDERNAME=$1
shift
TARGET_DEVICE=$1
shift
TARGET_DEVICE_PORT=$1
shift
TARGET_DEVICE_HOME=$1
shift
TARGET_DEVICE_USERNAME=$1
shift


set +e
echo "Lets create the click package for the project using cmake."
echo "${@}"
${SCRIPTPATH}/qtc_cmakeproject_click_create $@ > /tmp/qtc_click_create.log

if [[ $? -eq 0 ]]; then
	set -e
	PACKAGENAME=`cat /tmp/qtc_click_create.log|tail -n1`
	echo "$PACKAGENAME has been created."
else
	cat /tmp/qtc_click_create.log
	exit -1
fi

${SCRIPTPATH}/qtc_project_click_deploy ${SERIALNUMBER} ${PACKAGENAME} ${TARGET_DEVICE} ${TARGET_DEVICE_PORT} ${TARGET_DEVICE_HOME} ${TARGET_DEVICE_USERNAME}

