#!/bin/bash
# Copyright 2014 Canonical Ltd.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; version 2.1.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Author: Benjamin Zeller <benjamin.zeller@canonical.com>

SCRIPTPATH=$(dirname $0)
. `dirname $0`/functions.inc

FOLDERNAME=$2
TARGET_DEVICE=$3
TARGET_DEVICE_PORT=$4
TARGET_DEVICE_HOME=$5
BUILDTARGETS=$6

USAGE="$0 [serialnumber] [foldername] [target_device] [target_device_port] [target_device_home]"

if [[ -z $FOLDERNAME ]]; then
  echo ${USAGE}
  exit
fi

${SCRIPTPATH}/qtc_device_build_go "${1}" "${FOLDERNAME}" "${TARGET_DEVICE}" "${TARGET_DEVICE_PORT}" "${TARGET_DEVICE_HOME}" "${BUILDTARGETS}"

echo "Building package"
pushd "${FOLDERNAME}/click"
${SCRIPTPATH}/qtc_fix_desktop_comment $(${SCRIPTPATH}/qtc_find_desktopfile ${FOLDERNAME})
popd

click build "${FOLDERNAME}/click"


