#!/bin/bash
# Copyright 2014 Canonical Ltd.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; version 2.1.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Author: Benjamin Zeller<benjamin.zeller@canonical.com>


: ${CLICK_SDK_ARCH:?"Need to set CLICK_SDK_ARCH non-empty"}
: ${CLICK_SDK_FRAMEWORK:?"Need to set CLICK_SDK_FRAMEWORK non-empty"}
# : ${CLICK_SDK_SERIES:?"Need to set CLICK_SDK_SERIES non-empty"}

#architecture specific arguments
ARCH_ARGS=

if [ ${CLICK_SDK_ARCH} == "armhf" ]
then
    ARCH_ARGS='-DQT_IMPORTS_DIR=/usr/lib/arm-linux-gnueabihf/qt5/qml'
fi

rm  -rf CMakeFiles  CMakeCache.txt  cmake_install.cmake  Makefile

export QT_SELECT=qt5:$CLICK_SDK_ARCH
/usr/bin/click chroot -a $CLICK_SDK_ARCH -f $CLICK_SDK_FRAMEWORK run cmake -DINSTALL_TESTS=off -DCLICK_MODE=on ${ARCH_ARGS} "$@"


