#!/bin/bash
# Copyright 2014 Canonical Ltd.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; version 2.1.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Author: Benjamin Zeller <benjamin.zeller@canonical.com>

. `dirname $0`/functions.inc
shift

FOLDERNAME=$1
shift
TARGET_DEVICE=$1
shift
TARGET_DEVICE_PORT=$1
shift
TARGET_DEVICE_HOME=$1
shift
TARGET_DEVICE_USERNAME=$1
shift
BUILDTARGETS=$1
shift


set +e
echo "${@}"
${SCRIPTPATH}/qtc_device_buildpackage_go ${SERIALNUMBER} "${FOLDERNAME}" "${TARGET_DEVICE}" "${TARGET_DEVICE_PORT}" "${TARGET_DEVICE_HOME}" "${BUILDTARGETS}" > /tmp/qtc_click_create.log

if [[ $? -eq 0 ]]; then
	set -e
	PACKAGENAME=$(cat /tmp/qtc_click_create.log | tail -n1 | sed "s/^Successfully built package in //g;s/[']//g;s/.$//g")
	echo "$PACKAGENAME has been created."
else
	cat /tmp/qtc_click_create.log
	exit -1
fi

${SCRIPTPATH}/qtc_project_click_deploy ${SERIALNUMBER} ${PACKAGENAME} ${TARGET_DEVICE} ${TARGET_DEVICE_PORT} ${TARGET_DEVICE_HOME} ${TARGET_DEVICE_USERNAME}

