#!/bin/bash
# Copyright 2013 Canonical Ltd.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; version 2.1.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Author: Juhapekka Piiroinen <juhapekka.piiroinen@canonical.com>
# Author: Benjamin Zeller <benjamin.zeller@canonical.com>

SCRIPTPATH=$(dirname $0)

PROJECTNAME=$1

DESKTOPFILE_COUNT=`ls *.desktop|wc -l`
DESKTOPFILE=""
if [[ ${DESKTOPFILE_COUNT} -eq 1 ]]; then
    DESKTOPFILE=`ls *.desktop`
elif [[ ${DESKTOPFILE_COUNT} -eq 0 ]]; then
    exit 1
else
    # do we have a desktop file which has the same name as projectname
    if [[ -f ${PROJECTNAME}.desktop ]]; then
        # found one lets use it
        DESKTOPFILE=${PROJECTNAME}.desktop
    else
        # it seems that we did not have one, lets use the latest desktop file.
        DESKTOPFILE=`ls -t *.desktop|head -n1`
    fi
fi

echo "${DESKTOPFILE}"
exit 0
