#!/bin/bash
# Copyright 2013 Canonical Ltd.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; version 2.1.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Author: Juhapekka Piiroinen <juhapekka.piiroinen@canonical.com>

echo "Copying ubuntu-ui-toolkit-gallery from /usr/lib/ubuntu-ui-toolkit/examples to /tmp"
mkdir -p /tmp/ubuntu-ui-toolkit-gallery
cp -r /usr/lib/ubuntu-ui-toolkit/examples/ubuntu-ui-toolkit-gallery/* /tmp/ubuntu-ui-toolkit-gallery
echo "Opening project in Qt Creator"
qtcreator -client /tmp/ubuntu-ui-toolkit-gallery/ubuntu-ui-toolkit-gallery.qmlproject &
echo "Launching the qmlscene"
/usr/bin/qmlscene $@ /tmp/ubuntu-ui-toolkit-gallery/ubuntu-ui-toolkit-gallery.qml &
