#!/bin/bash
# Copyright 2013 Canonical Ltd.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; version 2.1.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Author: Juhapekka Piiroinen <juhapekka.piiroinen@canonical.com>

if [[ `dirname $0` =~ ubuntu-sdk-ide ]]; then
  echo Run from IDE
  EXAMPLES_PATH="$(/usr/ubuntu-sdk-dev/bin/qmake -query QT_INSTALL_EXAMPLES)/ubuntu-ui-toolkit/examples"
  export LD_LIBRARY_PATH=/usr/ubuntu-sdk-dev/lib/
  QMLSCENE="/usr/ubuntu-sdk-dev/bin/qmlscene"
else
  EXAMPLES_PATH="/usr/lib/ubuntu-ui-toolkit/examples"
  QMLSCENE="/usr/bin/qmlscene"
fi
if [ ! -d "${EXAMPLES_PATH}" ]
  then
    echo "Could not find the ubuntu-ui-toolkit examples, please make sure they are installed"
      exit 1
  fi
echo "Copying ubuntu-ui-toolkit-gallery from ${EXAMPLES_PATH} to /tmp"
mkdir -p /tmp/ubuntu-ui-toolkit-gallery
cp -r "${EXAMPLES_PATH}/ubuntu-ui-toolkit-gallery"/* /tmp/ubuntu-ui-toolkit-gallery
echo "Opening project in Qt Creator"
ubuntu-sdk -client /tmp/ubuntu-ui-toolkit-gallery/ubuntu-ui-toolkit-gallery.qmlproject &
echo "Launching the qmlscene"
$QMLSCENE $@ /tmp/ubuntu-ui-toolkit-gallery/ubuntu-ui-toolkit-gallery.qml &
