#!/bin/bash
# Copyright 2014 Canonical Ltd.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; version 2.1.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Author: Benjamin Zeller <benjamin.zeller@canonical.com>

. `dirname $0`/functions.inc

FOLDERNAME=$2
TARGET_DEVICE=$3
TARGET_DEVICE_PORT=$4
TARGET_DEVICE_HOME=$5

USAGE="$0 [serialnumber] [foldername] [target_device] [target_device_port] [target_device_home]"

set +e

#first build on the device
${SCRIPTPATH}/qtc_project_click_create ${FOLDERNAME} > /tmp/qtc_click_create.log

if [[ $? -eq 0 ]]; then
	set -e
	PACKAGENAME=$(cat /tmp/qtc_click_create.log | tail -n1)
	echo "$PACKAGENAME has been created."
else
	cat /tmp/qtc_click_create.log
	exit -1
fi

SCP="scp -i ${SSHIDENTITY} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -P${TARGET_DEVICE_PORT}"
SSH="ssh -i ${SSHIDENTITY} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p${TARGET_DEVICE_PORT} ${TARGET_DEVICE}"

adb -s ${SERIALNUMBER} push "${SCRIPTPATH}/qtc_device_applaunch.py" /tmp
adb -s ${SERIALNUMBER} push "${PACKAGENAME}" /tmp
$SSH "bash -ic 'source /etc/profile; /tmp/qtc_device_applaunch.py /tmp/$(basename ${PACKAGENAME})'"

